const obj= require('./logger')

const obj1= require('./util/helper')
const obj2=require('../vaildator/formatter')
const obj3=require('underscore')
const obj4=require('lodash')


obj.Fun("Ritu sharma")
obj.welFun()
console.log(obj.urlfun)
console.log('-----------------------')
obj1.getdate()
obj1.getmonth()
obj1.getcurrentInfo()
console.log('---------------------')
obj2.trim()
obj2.changetoLowerCase()
obj2.changetoUpperCase()
console.log('-----------------------------------')
console.log(obj3.first([12,34,12,34,54]))
console.log('---------------------------------')
console.log(obj4.chunk(["january","february","march","april","may","june","july","august","sep","oct","nov","dec"],3))
console.log('--------------')
console.log(obj4.tail([1,3,5,7,9,11,13,15,17,19]))
console.log('-----------------')
console.log(obj4.union([1,3],[1],[2,3],[4,6],[5,4]))
console.log('-------------')
console.log(obj4.fromPairs([['name','ritu'],['age',23],['location','delhi']]))